services:
  - type: web
    name: premier-predictor-pro
    env: docker
    plan: free 
    region: oregon 
    dockerContext: .
    dockerfilePath: Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 5001
      - key: PYTHONUNBUFFERED
        value: "true"
